# Generated by Django 5.0 on 2023-12-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="Nombre x", max_length=100)),
                ("categoria", models.CharField(default="Categoria x", max_length=100)),
                ("codigo", models.FloatField()),
                ("precio", models.FloatField(default=100.0)),
            ],
            options={
                "db_table": "product_table",
            },
        ),
    ]
